sed -i \
 -e 's/^CONFIG_RAETH_ESW_PORT_WAN=4$/CONFIG_RAETH_ESW_PORT_WAN=0/' \
 -e 's/^CONFIG_RAETH_ESW_PORT_LAN1=0$/CONFIG_RAETH_ESW_PORT_LAN1=1/' \
 -e 's/^CONFIG_RAETH_ESW_PORT_LAN2=1$/CONFIG_RAETH_ESW_PORT_LAN2=2/' \
 -e 's/^CONFIG_RAETH_ESW_PORT_LAN3=2$/CONFIG_RAETH_ESW_PORT_LAN3=3/' \
 -e 's/^CONFIG_RAETH_ESW_PORT_LAN4=3$/CONFIG_RAETH_ESW_PORT_LAN4=4/' \
 padavan-ng/trunk/configs/boards/TPLINK/TL_WR841N-V14/kernel-3.4.x.config
 
